name: "lint protobuf"
on: [pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v1

      - name: run protolint
        uses: plexsystems/protolint-action@v0.4.0
        with:
          configDirectory: config
